[package]
name = "rust-git"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = {version = "4.5.41", features = ["derive"]}
flate2 = "1.1.2"
hex = "0.4.3"
is_executable = "1.0.4"
sha1 = "0.10.6"
